# Generated by Django 4.0.7 on 2023-05-05 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='copy',
        ),
        migrations.AlterField(
            model_name='book',
            name='follow',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follows', to='books.follow'),
        ),
    ]
