# Generated by Django 4.0.7 on 2023-05-05 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Copy',
        ),
        migrations.DeleteModel(
            name='Loan',
        ),
    ]
