# Generated by Django 4.0.7 on 2023-05-05 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_remove_book_copy_alter_book_follow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Copy',
        ),
        migrations.DeleteModel(
            name='Loan',
        ),
        migrations.AddField(
            model_name='book',
            name='copies_count',
            field=models.IntegerField(default=0),
        ),
    ]
