# Generated by Django 4.0.7 on 2023-05-10 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='copies_count',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=80),
        ),
    ]
