# Generated by Django 4.0.7 on 2023-05-05 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0003_delete_copy_delete_loan_book_copies_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='copies_count',
        ),
        migrations.RemoveField(
            model_name='book',
            name='follow',
        ),
        migrations.AddField(
            model_name='follow',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follows', to='books.book'),
        ),
        migrations.AddField(
            model_name='follow',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follows', to=settings.AUTH_USER_MODEL),
        ),
    ]
