# Generated by Django 4.0.7 on 2023-05-05 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='copy',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
